version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
      POSTGRES_DB: portfolio_site
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
