import { BarChart3, Code2, Globe2, Workflow } from "lucide-react"
import { LeadCta } from "@/components/lead-cta"

const services = [
  { icon: Code2, title: "Sistemas adaptados à realidade da sua empresa", description: "Aplicações web, plataformas administrativas, portais e sistemas internos desenvolvidos conforme os processos, usuários e integrações do negócio.", examples: ["Sistemas administrativos", "Portais e áreas de clientes", "Sistemas de pedidos", "Aplicações SaaS", "Modernização de sistemas"], cta: "Avaliar meu sistema", source: "service_system" },
  { icon: Workflow, title: "Automatize tarefas e conecte seus canais", description: "Fluxos personalizados para conectar WhatsApp, Telegram, e-mail, formulários, planilhas, APIs, CRMs, ERPs e sistemas internos.", examples: ["Recepção e qualificação de leads", "Follow-up e confirmações", "Registro em CRM", "Alertas e relatórios", "Fluxos de aprovação"], cta: "Quero automatizar um processo", source: "service_automation" },
  { icon: Globe2, title: "Sites preparados para apresentar e gerar oportunidades", description: "Sites profissionais e landing pages com foco em credibilidade, velocidade, SEO, experiência mobile e geração de contatos.", examples: ["Sites institucionais", "Landing pages", "Catálogos", "Páginas de campanha", "WhatsApp, CRM e Analytics"], cta: "Solicitar proposta do site", source: "service_site" },
  { icon: BarChart3, title: "Informações organizadas para decisões mais claras", description: "Dashboards e relatórios que centralizam informações operacionais, comerciais e administrativas.", examples: ["Indicadores comerciais", "Dados operacionais", "Relatórios administrativos", "Integração de fontes", "Painéis de acompanhamento"], cta: "Organizar meus dados", source: "service_data" },
]

export function ServicesSection() { return <section id="solutions" className="scroll-mt-24 py-20 sm:py-24"><div className="container mx-auto px-4"><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><p className="section-eyebrow">Soluções STech</p><h2 className="section-title">Do processo manual à solução conectada</h2><p className="section-copy">A STech analisa o cenário, identifica oportunidades e desenvolve a solução adequada — seja um sistema, um site, uma integração ou uma automação.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2">{services.map(({ icon: Icon, ...service }, index) => <article key={service.title} className={`rounded-2xl border bg-card p-6 sm:p-7 ${index === 1 ? "border-[var(--brand-cyan)]/60" : "border-border"}`}><Icon className="h-8 w-8 text-[var(--brand-cyan)]" aria-hidden="true" /><h3 className="mt-4 text-xl font-semibold">{service.title}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{service.description}</p><ul className="mt-5 grid gap-2 text-sm sm:grid-cols-2">{service.examples.map((item) => <li key={item} className="rounded-lg bg-background/70 px-3 py-2">{item}</li>)}</ul><LeadCta source={service.source} initialMessage={`Gostaria de conversar sobre: ${service.title}.`} label={service.cta} className="mt-6 w-full sm:w-auto" /></article>)}</div></div></div></section> }
